# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Fetch Github Release Asset
      uses: dsaltares/fetch-gh-release-asset@1.0.0
      with:
        repo: 'smckeon-so/play-with-gh-actions'
        regex: true
        file: '*.txt'
        
    - run: ls -al
      
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
#       Fetch UI assets - somehow

#       Copy them into the app dir
#       Build prod app
        
    - run: npm ci
    - run: npm run make
