# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: zip/darwin/x64/electron-quick-start-darwin-x64-1.0.0.zip
          - os: ubuntu-latest
            artifact_name: mything
          - os: windows-latest
            artifact_name: mything.exe


    steps:      
    - uses: actions/checkout@v3

        # Fetch UI assets - somehow
    - name: Fetch Github Release Asset
      uses: dsaltares/fetch-gh-release-asset@1.0.0
      with:
        repo: 'smckeon-so/play-with-gh-actions'
        version: 'tags/main'
        file: 'ui-build-artifacts.zip'

    - run: unzip ui-build-artifacts.zip
    # Copy assets into the app src
    - run: mv build/* .

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'

    - run: npm ci
    # Build prod app
    - run: npm run make

    
    - run: tree out/make
      if: ${{matrix.os == 'ubuntu-latest'}} 

    # upload mac build to release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/make/${{ matrix.artifact_name }}
        tag: ${{ github.ref }}
        overwrite: true
        body: "Final build artifacts"


